// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4q2LjcKRqyT17jKLkDIY-27iECAigt6k',
    appId: '1:120157599815:web:f7f73302722ae80bcb5962',
    messagingSenderId: '120157599815',
    projectId: 'javacrud-902f2',
    authDomain: 'javacrud-902f2.firebaseapp.com',
    storageBucket: 'javacrud-902f2.appspot.com',
    measurementId: 'G-43SR6W2C2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK_95DmAKLR2NoAbjootwBzNI-Jy4oSEQ',
    appId: '1:120157599815:android:03486975c64934dacb5962',
    messagingSenderId: '120157599815',
    projectId: 'javacrud-902f2',
    storageBucket: 'javacrud-902f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5thHs5xS7J_B5cDyzXLrjCy-wC_W5M40',
    appId: '1:120157599815:ios:9a89db43d5834352cb5962',
    messagingSenderId: '120157599815',
    projectId: 'javacrud-902f2',
    storageBucket: 'javacrud-902f2.appspot.com',
    iosBundleId: 'com.example.tasklyplatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5thHs5xS7J_B5cDyzXLrjCy-wC_W5M40',
    appId: '1:120157599815:ios:9a89db43d5834352cb5962',
    messagingSenderId: '120157599815',
    projectId: 'javacrud-902f2',
    storageBucket: 'javacrud-902f2.appspot.com',
    iosBundleId: 'com.example.tasklyplatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4q2LjcKRqyT17jKLkDIY-27iECAigt6k',
    appId: '1:120157599815:web:e478f554c1be2d0bcb5962',
    messagingSenderId: '120157599815',
    projectId: 'javacrud-902f2',
    authDomain: 'javacrud-902f2.firebaseapp.com',
    storageBucket: 'javacrud-902f2.appspot.com',
    measurementId: 'G-51YNB6H6GM',
  );
}
